// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enum/enum_cz.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "enum/enum_cz.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace PKENUM {

namespace {

const ::google::protobuf::EnumDescriptor* CZPacketEnum_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_enum_2fenum_5fcz_2eproto() {
  protobuf_AddDesc_enum_2fenum_5fcz_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "enum/enum_cz.proto");
  GOOGLE_CHECK(file != NULL);
  CZPacketEnum_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_enum_2fenum_5fcz_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_enum_2fenum_5fcz_2eproto() {
}

void protobuf_AddDesc_enum_2fenum_5fcz_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022enum/enum_cz.proto\022\006PKENUM*\302\001\n\014CZPacke"
    "tEnum\022\r\n\010CZ_BEGIN\020\310\001\022\014\n\007CZ_MOVE\020\311\001\022\014\n\007CZ"
    "_STOP\020\312\001\022\r\n\010CZ_EVADE\020\313\001\022\022\n\rCZ_ENTER_GAME"
    "\020\322\001\022\016\n\tCZ_ATTACK\020\323\001\022\022\n\rCZ_ATTACK_HIT\020\324\001\022"
    "\016\n\tCZ_REVIVE\020\325\001\022\025\n\020CZ_USE_HP_POTION\020\326\001\022\014"
    "\n\007CZ_PING\020\252\002\022\013\n\006CZ_END\020\253\002", 225);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "enum/enum_cz.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_enum_2fenum_5fcz_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_enum_2fenum_5fcz_2eproto {
  StaticDescriptorInitializer_enum_2fenum_5fcz_2eproto() {
    protobuf_AddDesc_enum_2fenum_5fcz_2eproto();
  }
} static_descriptor_initializer_enum_2fenum_5fcz_2eproto_;
const ::google::protobuf::EnumDescriptor* CZPacketEnum_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CZPacketEnum_descriptor_;
}
bool CZPacketEnum_IsValid(int value) {
  switch(value) {
    case 200:
    case 201:
    case 202:
    case 203:
    case 210:
    case 211:
    case 212:
    case 213:
    case 214:
    case 298:
    case 299:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace PKENUM

// @@protoc_insertion_point(global_scope)
