// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enum/enum_cm.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "enum/enum_cm.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace PKENUM {

namespace {

const ::google::protobuf::EnumDescriptor* CMPacketEnum_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_enum_2fenum_5fcm_2eproto() {
  protobuf_AddDesc_enum_2fenum_5fcm_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "enum/enum_cm.proto");
  GOOGLE_CHECK(file != NULL);
  CMPacketEnum_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_enum_2fenum_5fcm_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_enum_2fenum_5fcm_2eproto() {
}

void protobuf_AddDesc_enum_2fenum_5fcm_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022enum/enum_cm.proto\022\006PKENUM*b\n\014CMPacket"
    "Enum\022\014\n\010CM_BEGIN\020\000\022\022\n\016CM_JOIN_MEMBER\020\001\022\014"
    "\n\010CM_LOGIN\020\002\022\026\n\022CM_SET_FAMILY_NAME\020\003\022\n\n\006"
    "CM_END\020c", 128);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "enum/enum_cm.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_enum_2fenum_5fcm_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_enum_2fenum_5fcm_2eproto {
  StaticDescriptorInitializer_enum_2fenum_5fcm_2eproto() {
    protobuf_AddDesc_enum_2fenum_5fcm_2eproto();
  }
} static_descriptor_initializer_enum_2fenum_5fcm_2eproto_;
const ::google::protobuf::EnumDescriptor* CMPacketEnum_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CMPacketEnum_descriptor_;
}
bool CMPacketEnum_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 99:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace PKENUM

// @@protoc_insertion_point(global_scope)
