// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enum/enum_cm.proto

#ifndef PROTOBUF_enum_2fenum_5fcm_2eproto__INCLUDED
#define PROTOBUF_enum_2fenum_5fcm_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace PKENUM {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_enum_2fenum_5fcm_2eproto();
void protobuf_AssignDesc_enum_2fenum_5fcm_2eproto();
void protobuf_ShutdownFile_enum_2fenum_5fcm_2eproto();


enum CMPacketEnum {
  CM_BEGIN = 0,
  CM_JOIN_MEMBER = 1,
  CM_LOGIN = 2,
  CM_SET_FAMILY_NAME = 3,
  CM_END = 99
};
bool CMPacketEnum_IsValid(int value);
const CMPacketEnum CMPacketEnum_MIN = CM_BEGIN;
const CMPacketEnum CMPacketEnum_MAX = CM_END;
const int CMPacketEnum_ARRAYSIZE = CMPacketEnum_MAX + 1;

const ::google::protobuf::EnumDescriptor* CMPacketEnum_descriptor();
inline const ::std::string& CMPacketEnum_Name(CMPacketEnum value) {
  return ::google::protobuf::internal::NameOfEnum(
    CMPacketEnum_descriptor(), value);
}
inline bool CMPacketEnum_Parse(
    const ::std::string& name, CMPacketEnum* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CMPacketEnum>(
    CMPacketEnum_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace PKENUM

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::PKENUM::CMPacketEnum> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PKENUM::CMPacketEnum>() {
  return ::PKENUM::CMPacketEnum_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_enum_2fenum_5fcm_2eproto__INCLUDED
