// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enum/enum_mc.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "enum/enum_mc.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace PKENUM {

namespace {

const ::google::protobuf::EnumDescriptor* MCPacketEnum_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_enum_2fenum_5fmc_2eproto() {
  protobuf_AddDesc_enum_2fenum_5fmc_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "enum/enum_mc.proto");
  GOOGLE_CHECK(file != NULL);
  MCPacketEnum_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_enum_2fenum_5fmc_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_enum_2fenum_5fmc_2eproto() {
}

void protobuf_AddDesc_enum_2fenum_5fmc_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022enum/enum_mc.proto\022\006PKENUM*x\n\014MCPacket"
    "Enum\022\014\n\010MC_BEGIN\020d\022\031\n\025MC_JOIN_MEMBER_RES"
    "ULT\020e\022\023\n\017MC_LOGIN_RESULT\020f\022\035\n\031MC_SET_FAM"
    "ILY_NAME_RESULT\020g\022\013\n\006MC_END\020\307\001", 150);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "enum/enum_mc.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_enum_2fenum_5fmc_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_enum_2fenum_5fmc_2eproto {
  StaticDescriptorInitializer_enum_2fenum_5fmc_2eproto() {
    protobuf_AddDesc_enum_2fenum_5fmc_2eproto();
  }
} static_descriptor_initializer_enum_2fenum_5fmc_2eproto_;
const ::google::protobuf::EnumDescriptor* MCPacketEnum_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MCPacketEnum_descriptor_;
}
bool MCPacketEnum_IsValid(int value) {
  switch(value) {
    case 100:
    case 101:
    case 102:
    case 103:
    case 199:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace PKENUM

// @@protoc_insertion_point(global_scope)
