// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enum/enum_zc.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "enum/enum_zc.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace PKENUM {

namespace {

const ::google::protobuf::EnumDescriptor* ZCPacketEnum_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_enum_2fenum_5fzc_2eproto() {
  protobuf_AddDesc_enum_2fenum_5fzc_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "enum/enum_zc.proto");
  GOOGLE_CHECK(file != NULL);
  ZCPacketEnum_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_enum_2fenum_5fzc_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_enum_2fenum_5fzc_2eproto() {
}

void protobuf_AddDesc_enum_2fenum_5fzc_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022enum/enum_zc.proto\022\006PKENUM*\370\002\n\014ZCPacke"
    "tEnum\022\r\n\010ZC_BEGIN\020\254\002\022\024\n\017ZC_ME_CONNECTED\020"
    "\255\002\022\034\n\027ZC_OTHER_USER_CONNECTED\020\256\002\022\036\n\031ZC_E"
    "XIST_USER_INFORMATION\020\257\002\022\031\n\024ZC_USER_DISC"
    "ONNECTED\020\260\002\022\030\n\023ZC_MONSTER_APPEARED\020\261\002\022\014\n"
    "\007ZC_MOVE\020\266\002\022\021\n\014ZC_MOVE_DEST\020\267\002\022\014\n\007ZC_STO"
    "P\020\270\002\022\r\n\010ZC_EVADE\020\271\002\022\014\n\007ZC_DIED\020\272\002\022\023\n\016ZC_"
    "ENTER_FIELD\020\300\002\022\016\n\tZC_ATTACK\020\312\002\022\017\n\nZC_GET"
    "_HIT\020\313\002\022\014\n\007ZC_DEAD\020\314\002\022\016\n\tZC_REVIVE\020\315\002\022\025\n"
    "\020ZC_USE_HP_POTION\020\316\002\022\014\n\007ZC_PING\020\216\003\022\013\n\006ZC"
    "_END\020\217\003", 407);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "enum/enum_zc.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_enum_2fenum_5fzc_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_enum_2fenum_5fzc_2eproto {
  StaticDescriptorInitializer_enum_2fenum_5fzc_2eproto() {
    protobuf_AddDesc_enum_2fenum_5fzc_2eproto();
  }
} static_descriptor_initializer_enum_2fenum_5fzc_2eproto_;
const ::google::protobuf::EnumDescriptor* ZCPacketEnum_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ZCPacketEnum_descriptor_;
}
bool ZCPacketEnum_IsValid(int value) {
  switch(value) {
    case 300:
    case 301:
    case 302:
    case 303:
    case 304:
    case 305:
    case 310:
    case 311:
    case 312:
    case 313:
    case 314:
    case 320:
    case 330:
    case 331:
    case 332:
    case 333:
    case 334:
    case 398:
    case 399:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace PKENUM

// @@protoc_insertion_point(global_scope)
