// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enum/enum_mc.proto

#ifndef PROTOBUF_enum_2fenum_5fmc_2eproto__INCLUDED
#define PROTOBUF_enum_2fenum_5fmc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace PKENUM {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_enum_2fenum_5fmc_2eproto();
void protobuf_AssignDesc_enum_2fenum_5fmc_2eproto();
void protobuf_ShutdownFile_enum_2fenum_5fmc_2eproto();


enum MCPacketEnum {
  MC_BEGIN = 100,
  MC_JOIN_MEMBER_RESULT = 101,
  MC_LOGIN_RESULT = 102,
  MC_SET_FAMILY_NAME_RESULT = 103,
  MC_END = 199
};
bool MCPacketEnum_IsValid(int value);
const MCPacketEnum MCPacketEnum_MIN = MC_BEGIN;
const MCPacketEnum MCPacketEnum_MAX = MC_END;
const int MCPacketEnum_ARRAYSIZE = MCPacketEnum_MAX + 1;

const ::google::protobuf::EnumDescriptor* MCPacketEnum_descriptor();
inline const ::std::string& MCPacketEnum_Name(MCPacketEnum value) {
  return ::google::protobuf::internal::NameOfEnum(
    MCPacketEnum_descriptor(), value);
}
inline bool MCPacketEnum_Parse(
    const ::std::string& name, MCPacketEnum* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MCPacketEnum>(
    MCPacketEnum_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace PKENUM

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::PKENUM::MCPacketEnum> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PKENUM::MCPacketEnum>() {
  return ::PKENUM::MCPacketEnum_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_enum_2fenum_5fmc_2eproto__INCLUDED
